os: linux
dist: xenial
language: python
python:
  - "3.6"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++
      - gcc
      - build-essential
      - python-dev
      - libnetfilter-queue-dev
install:
  - pip install scapy==2.4.0
script:
  - python --version
deploy:
  provider: pypi
  user:
    secure: "t1aUH/3MgRvar2M2OcJfsEB7kYvr9bxQgk/NSWORt1zrOC2tvRdmR+ukSmJAIDgH5I8uMb2NtOKEuZr+O6EXZBIQJsvH5acpxAPOmwJWucA8Nab5ELNyPhZK0lxGOh4WfQEMbZNjdt3DybwxuygR10twoc4fVJIhKd6JkWbsKWOx2bZZNPr6xfXtZvSOUCNGR9apQJTHNJ6lLRS4HtnamLOk+a+Uu4n1jsG2txpZNQQM9O/gndm5Sob8Ci9zfiHoSyd/yAtjEsxBj/WWc0hyjOQ5gBmg31bShjCXy3Gd4dhvPIPBo/KQHqfr5zyfpBeWB8Sj/DX1HblyuIUGHowJalx9HkctivpQwEcDuJsSsblSdXZTYx1PZIFteXAezLQY+wKd6D21wco+fHEGp21DvPNpmHg8kTW7aZCdSVbZRRUc7ChHRlewcy2Jvu8Umf4QoUfHJfNWhuwsS6VQh14cGyq9N+LvMQeZzK81KWSRb21l/swnafHP3cCzoxYp+feVhTkz+k6a5XX+3UzzD09JSCjBgtgx5FGLQOvJzW6KRQmqIgRthP4WqbBo4e7M7E9K1YTnc8vNTjQO0VWjHri83+sugWratLj0imYolJJeYnMhRAXnSyiw4drEKkj7R2HO6iVktfK3bZA+WLlBA1Y8qA7SS9O5Hyr4cbFU1AFEuXk="
  server: https://test.pypi.org/legacy/
  password:
    secure: "VllS+XIgbxbvpHVn10PqHw1gn1TqM7HzycTgqUJRMNxX32AQFnuITPQWOEZXSN1RMAI7h3UhvDP2IwP6PEnxfGKqx3hgC/Yd4VAnypfNDr9lKitys7Nmp+JY8p4yWFjBGXjxj3IUstGpdG8CpSv1fKsCGWhf1H4JVA2ufKk9XSioe3cadcJSCuib/OVCZL/6dLzUsQsBnlS8Xq1WbxyBd3VsAW40IHQ9ChfMgXCPodTSNeEM26vxB7WLEYHvvfw/+/45NuMBu14Gc6YuUk1Pgg0lsUvCyfppR76LesUYpD5VB7XSC8wHay97hJ+NT2M4fUIDMcOHYjHSYT/eSNuHjyv0OaXqksmii6nwR3/av3ovUXInVIuqTGRK+7YVyqrblk3G/oRwBZgPLQRFh0xItufLSwS1nm6WHal7Lbsk9WbY2LJvGCY3940/Nh+skWm6jN/uMFipYCjl+1evtmth1sbmmrb4wnaabJsYjeuEV+ZfWx+3xIHOra7R57c2388vi8lvSenuw/CHAubgxj1b8UbHPRe5FHgAu2AjwsLFpIdt3F4R6oZM+kAJzjzq0w8kUuLotqk03bEl0/HoeQHapxTga9BsDz9lwXcn7guMikIheQ1iWK/8mt1lKuxrIsP0fbzGddQsaYupqzkQ4Fw3RnE8HwhNX+YeUK1b2V1TEes="
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    branch: master
    repo: OWASP/SecureTea-Project